spring:
  datasource:
    url: jdbc:mysql://localhost:3306/milk_store_ecom?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: validate
  sql:
    init.mode: never
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  error.include-stacktrace: never

